FROM python:3.11

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt 

COPY . .

RUN pip install celery

CMD ["python", "manage.py", "runserver", "0.0.0:8000.0"]

ENV PYTHONUNBUFFERED=1