# Generated by Django 5.0.6 on 2024-06-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTime', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
